name: Action name
description: |
  Action description
author: KOLANICH

inputs: 
  name:
    description: 'Artifact name'
    default: 'artifact'
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
  if-no-files-found:
    default: 'warn'
  retention-days:
    description: >
      a

runs:
  using: "node12" # GitHub disallows to use anything other there
  main: "startBash.js" # ECMA modules are not yet supported by GH Actions

branding:
  icon: check-square
  color: green
